### LIST ALL PRODUCTS
GET http://localhost:3000/products

### LIST ALL PRODUCTS FILTERED BY NAME
GET http://localhost:3000/products
Content-Type: application/json

{
  "search": "esg-social-empreendedorasdabeleza"
}

### CREATE A NEW PRODUCT
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "esg-social-empreendedorasdabeleza"
}

// PRODUCT ID FOR THE NEXT REQUESTS
@productId = 08dc7c25-d9a1-43ec-884b-682eb0bd8bef

### GET ALL PERMISSIONS FOR A PRODUCT
GET http://localhost:3000/products/{{productId}}/permissions

### ADD A NEW MEMBER TO A PRODUCT
POST http://localhost:3000/products/{{productId}}/members
Content-Type: application/json

{
  "emails": ["samuel.dutra@grupoboticario.com.br"],
  "permission": "Administrators"
}
