### LIST ALL PRODUCTS
GET http://localhost:3000/products

### LIST ALL PRODUCTS FILTERED BY NAME
GET http://localhost:3000/products
Content-Type: application/json

{
  "search": "plataforma ecomm"
}

### CREATE A NEW PRODUCT
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "cnp-conecta-prices"
}

### 
// PRODUCT ID FOR THE NEXT REQUESTS
@productId = 08d91f71-87c6-4f4e-8e27-254ea564e90d

### GET ALL PERMISSIONS FOR A PRODUCT
GET http://localhost:3000/products/{{productId}}/permissions

### ADD A NEW MEMBER TO A PRODUCT
POST http://localhost:3000/products/{{productId}}/members
Content-Type: application/json

{
  "emails": ["octavio.bolzani@grupoboticario.com.br"],
  "permission": "Administrators"
}
