version: '3.8'
services:
  redis:
    image: "redis/redis-stack:latest"
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
        - ./redis_data:/data
  configcat-proxy:
    image: "configcat/proxy:1.0.0"
    container_name: configcat-proxy
    ports:
      - "8050:8050"
      - "8051:8051"
      - "50051:50051"
    depends_on:
      - redis
    volumes:
      - "./docker/options.yaml:/etc/configcat/proxy/options.yml"
    env_file:
      - .env
