export const ALL_REPOS = 'allGithubRepos'
export const REPOS_WITH_COLLABORATORS = 'reposWithCollaborators'
export const REPOS_WITH_COLLABORATORS_IN_CSV = 'reposWithCollaboratorsInCsv'
export const REPOS_WITH_COLLABORATORS_ADMIN_IN_CSV = 'reposWithCollaboratorsAdmin'
export const COLLABORATOR_REMOVED_REPO = 'collaboratorRemovedRepo'
export const COLLABORATOR_REMOVED_REPO_ERRORS = 'collaboratorRemovedRepoErrors'